# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('unit', models.CharField(max_length=30, verbose_name='单位')),
                ('office', models.CharField(max_length=50, verbose_name='科室')),
                ('post', models.CharField(max_length=50, verbose_name='职务')),
                ('professional', models.CharField(max_length=50, verbose_name='职称')),
                ('number', models.CharField(max_length=50, verbose_name='工号')),
            ],
        ),
    ]
